### ISSUE TITLE
latest version on npm is 0.2.0

### ISSUE THREAD

**Issue by heavyk** [acornjs/acorn-private-class-elements#12]
... not 0.2.2 -- even though npm says that you published 22 days ago same that github says pushed the 0.2.2 version to github. I use acorn 7, so it's pretty necessary.

you must have mistakenly published the wrong version to npm.. the package.json has `"version": "0.2.0"`which is probably how it happened.  temporarily as a workaround I've set my package.json to point to this repository. just lettin you know, though..

cheers 👍

**Comment by jayaddison** [comment]
Hey @heavyk  - I'm seeing the same issue.  It looks like an accidental work-in-progress directory may have been uploaded to NPM.

Apart from one difference, [`0.2.0` on NPM](https://registry.npmjs.org/acorn-private-class-elements/-/acorn-private-class-elements-0.2.0.tgz)'s file contents are identical to [`0.2.2` on GitHub](https://github.com/acornjs/acorn-private-class-elements/releases/tag/0.2.2).  An extra `package-lock.json` file exists in the download from NPM.

The `package-lock.json` might be from an old checkout or other branch because it declares version `0.1.0`.  Hopefully it's a relatively straightforward cleanup and just requires a re-upload of `0.2.2` to the correct NPM tag.

**Comment by heavyk** [comment]
yeah, to get around it temporarily, add this to your `dependencies` in `package.json`

```
...
"acorn-private-class-elements": "github:heavyk/acorn-private-class-elements#patch-1",
...
```

that patch simply changes the version to be 0.2.2. I'm using yarn, and for whatever reason, it sees 0.2.0, gets confused and installs the 0.2.0 package, not the 0.2.2 one (which has the wrong version). I think it has to do with the yarn.lock pre-resolving the url of the package... kinda a funny bug

**Comment by adrianheine** [comment]
0.2.0 is the correct version, the wrong 0.2.2 only appears in the commit message. Edit: And there was a git tag, too.

**Comment by adrianheine** [comment]
Sorry about the package-lock.json, though :/

**Comment by jayaddison** [comment]
@adrianheine No problem, thanks for clarifying :)

Would you mind releasing a `0.2.3` (even if it contains only cosmetic or no changes at all) to clear up any future confusion?
